//! Cross-validation of our RIPMAP_LEVELS tiled encoder against the OpenEXR
//! reference binaries.
//!
//! The round-124 ripmap encoder writes single-part `RIPMAP_LEVELS` tiled
//! EXR files (`tiledesc.level_mode = 2`) carrying the full 2-D reduction
//! grid generated by separable 2× box filtering. We validate by:
//!
//! 1. Encoding a synthesised gradient with our `encode_exr_tiled_..._ripmap`.
//! 2. Asking `exrmetrics --convert -z none` to decode + re-encode the file
//!    as an uncompressed scanline file. If our chunks + offset table are
//!    spec-legal, that decode succeeds.
//! 3. Re-parsing the converted file with our own scanline decoder and
//!    confirming level-(0,0) RGBA matches the input pixel-exactly.
//!
//! `exrheader` is additionally invoked to confirm it reports `ripmap` as
//! the level mode. A reverse cross-check feeds a reference RIPMAP file made
//! by `exrmaketiled -r` back through our decoder and confirms we read its
//! level-(0,0) pixels (sanity on the level-grid offset-table walk).
//!
//! All tests auto-skip when the reference binaries are absent.

use std::process::Command;

use oxideav_openexr::{
    encode_exr_scanline_rgba_float, encode_exr_tiled_rgba_float_ripmap_box_filter, parse_exr,
    ripmap_level_counts_round_down, Compression,
};

fn tool_available(name: &str) -> bool {
    Command::new(name)
        .arg("--help")
        .output()
        .map(|o| o.status.code().is_some())
        .unwrap_or(false)
}

fn tempdir(tag: &str) -> std::path::PathBuf {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("oxideav-exr-ripmap-{tag}-{nanos}"));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

fn make_image(w: u32, h: u32) -> Vec<f32> {
    let mut s = Vec::with_capacity((w * h * 4) as usize);
    for y in 0..h {
        for x in 0..w {
            s.push(x as f32 / w as f32);
            s.push(y as f32 / h as f32);
            s.push(((x ^ y) as f32) * 0.01);
            s.push(1.0);
        }
    }
    s
}

fn run_exrmetrics_roundtrip(compression: Compression, tag: &str) {
    if !tool_available("exrmetrics") {
        eprintln!("exrmetrics not found, skipping ripmap-encoder validation ({tag})");
        return;
    }
    // Non-square so x-levels and y-levels differ (48 -> 6 x-levels,
    // 32 -> 6 y-levels, but distinct level dims along each axis).
    let w = 48u32;
    let h = 32u32;
    let samples = make_image(w, h);
    let our_bytes =
        encode_exr_tiled_rgba_float_ripmap_box_filter(w, h, &samples, compression, 16, 16)
            .expect("our ripmap encoder failed");

    let dir = tempdir(tag);
    let our_path = dir.join(format!("ours_{tag}.exr"));
    let conv_path = dir.join(format!("conv_{tag}.exr"));
    std::fs::write(&our_path, &our_bytes).unwrap();

    let output = Command::new("exrmetrics")
        .args([
            "--convert",
            "-z",
            "none",
            our_path.to_str().unwrap(),
            "-o",
            conv_path.to_str().unwrap(),
        ])
        .output()
        .expect("exrmetrics --convert spawn failed");
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        panic!(
            "exrmetrics --convert refused our ripmap file ({tag}): status={:?}\nstderr: {stderr}\nstdout: {stdout}",
            output.status
        );
    }

    let conv_bytes = std::fs::read(&conv_path).unwrap();
    let img = parse_exr(&conv_bytes).expect("parse_exr on converted file failed");
    assert_eq!(img.width(), w, "converted width mismatch ({tag})");
    assert_eq!(img.height(), h, "converted height mismatch ({tag})");

    let a = &img.planes[0].samples;
    let b = &img.planes[1].samples;
    let g = &img.planes[2].samples;
    let r = &img.planes[3].samples;
    for y in 0..h as usize {
        for x in 0..w as usize {
            let off = y * w as usize + x;
            assert!(
                (r[off] - samples[off * 4]).abs() < 1e-6,
                "R mismatch at ({x},{y}) ({tag})"
            );
            assert!(
                (g[off] - samples[off * 4 + 1]).abs() < 1e-6,
                "G mismatch at ({x},{y}) ({tag})"
            );
            assert!(
                (b[off] - samples[off * 4 + 2]).abs() < 1e-6,
                "B mismatch at ({x},{y}) ({tag})"
            );
            assert!(
                (a[off] - samples[off * 4 + 3]).abs() < 1e-6,
                "A mismatch at ({x},{y}) ({tag})"
            );
        }
    }

    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn ripmap_encoder_exrmetrics_accepts_none() {
    run_exrmetrics_roundtrip(Compression::None, "none");
}

#[test]
fn ripmap_encoder_exrmetrics_accepts_zip() {
    run_exrmetrics_roundtrip(Compression::Zip, "zip");
}

#[test]
fn ripmap_encoder_exrmetrics_accepts_zips() {
    run_exrmetrics_roundtrip(Compression::Zips, "zips");
}

#[test]
fn ripmap_encoder_exrmetrics_accepts_rle() {
    run_exrmetrics_roundtrip(Compression::Rle, "rle");
}

#[test]
fn ripmap_encoder_exrheader_reports_ripmap_levels() {
    if !tool_available("exrheader") {
        eprintln!("exrheader not found, skipping ripmap header check");
        return;
    }
    let w = 48u32;
    let h = 32u32;
    let samples = make_image(w, h);
    let our_bytes =
        encode_exr_tiled_rgba_float_ripmap_box_filter(w, h, &samples, Compression::Zip, 16, 16)
            .expect("our ripmap encoder failed");

    let dir = tempdir("header");
    let path = dir.join("ripmap.exr");
    std::fs::write(&path, &our_bytes).unwrap();

    let output = Command::new("exrheader")
        .arg(path.to_str().unwrap())
        .output()
        .expect("exrheader spawn failed");
    assert!(
        output.status.success(),
        "exrheader failed on our file: status={:?}\nstderr: {}\nstdout: {}",
        output.status,
        String::from_utf8_lossy(&output.stderr),
        String::from_utf8_lossy(&output.stdout)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    let lower = stdout.to_lowercase();
    assert!(
        lower.contains("ripmap"),
        "exrheader output did not mention ripmap: {stdout}"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// Feed a reference RIPMAP file produced by `exrmaketiled -r` back through
/// our decoder and confirm we recover its level-(0,0) pixels. This pins our
/// 2-D level-grid offset-table walk against the reference encoder.
#[test]
fn ripmap_decoder_reads_exrmaketiled_reference() {
    if !tool_available("exrmaketiled") {
        eprintln!("exrmaketiled not found, skipping reference ripmap decode check");
        return;
    }
    let w = 48u32;
    let h = 32u32;
    let samples = make_image(w, h);

    // Start from a plain scanline EXR (uncompressed) written by our encoder.
    let base = encode_exr_scanline_rgba_float(w, h, &samples).expect("scanline encode failed");

    let dir = tempdir("ref");
    let base_path = dir.join("base.exr");
    let rip_path = dir.join("ref_ripmap.exr");
    std::fs::write(&base_path, &base).unwrap();

    // -r ripmap, -z none uncompressed, default ROUND_DOWN, 16×16 tiles.
    let output = Command::new("exrmaketiled")
        .args([
            "-r",
            "-z",
            "none",
            "-t",
            "16",
            "16",
            base_path.to_str().unwrap(),
            rip_path.to_str().unwrap(),
        ])
        .output()
        .expect("exrmaketiled spawn failed");
    assert!(
        output.status.success(),
        "exrmaketiled -r failed: status={:?}\nstderr: {}\nstdout: {}",
        output.status,
        String::from_utf8_lossy(&output.stderr),
        String::from_utf8_lossy(&output.stdout)
    );

    let rip_bytes = std::fs::read(&rip_path).unwrap();
    let img = parse_exr(&rip_bytes).expect("parse_exr on reference ripmap failed");
    assert_eq!(img.width(), w, "reference ripmap width mismatch");
    assert_eq!(img.height(), h, "reference ripmap height mismatch");

    // exrmaketiled may emit the channels in HALF; our base is FLOAT and
    // exrmaketiled preserves the pixel type when re-tiling, so level-(0,0)
    // should match the original float samples bit-near.
    let a = &img.planes[0].samples;
    let b = &img.planes[1].samples;
    let g = &img.planes[2].samples;
    let r = &img.planes[3].samples;
    for y in 0..h as usize {
        for x in 0..w as usize {
            let off = y * w as usize + x;
            assert!(
                (r[off] - samples[off * 4]).abs() < 1e-4,
                "ref R mismatch at ({x},{y})"
            );
            assert!(
                (g[off] - samples[off * 4 + 1]).abs() < 1e-4,
                "ref G mismatch at ({x},{y})"
            );
            assert!(
                (b[off] - samples[off * 4 + 2]).abs() < 1e-4,
                "ref B mismatch at ({x},{y})"
            );
            assert!(
                (a[off] - samples[off * 4 + 3]).abs() < 1e-4,
                "ref A mismatch at ({x},{y})"
            );
        }
    }

    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn ripmap_level_counts_helper() {
    // 48 -> 48,24,12,6,3,1 = 6 x-levels; 32 -> 32,16,8,4,2,1 = 6 y-levels.
    assert_eq!(ripmap_level_counts_round_down(48, 32), (6, 6));
    // 16×8 -> x: 16,8,4,2,1 = 5; y: 8,4,2,1 = 4.
    assert_eq!(ripmap_level_counts_round_down(16, 8), (5, 4));
    assert_eq!(ripmap_level_counts_round_down(1, 1), (1, 1));
    // 7 -> 7,3,1 = 3.
    assert_eq!(ripmap_level_counts_round_down(7, 7), (3, 3));
}
